name: proyecto_final_bases
version: 1.0.0+1
publish_to: none
description: Módulo para la gestión de los teatro de la UD
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  firebase_messaging: ^11.2.10
  cloud_functions: ^3.2.10

  #Get
  get: 4.6.1
  get_storage: 2.0.3

  # Others
  dots_indicator: ^2.1.0
  syncfusion_flutter_datepicker: ^19.4.54
  intl: ^0.17.0
  url_launcher: ^6.0.20
  material_design_icons_flutter:
  permission_handler: ^9.2.0
  cached_network_image: ^3.2.0
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  flutter_multi_formatter: ^2.5.1
  mailer: ^5.1.0
  smtpd: ^0.2.0
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
